// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT31pDztqFzVW6x0EORiPwrKKPPXpniUQ',
    appId: '1:1092944111670:web:89c739eadba8c68e015097',
    messagingSenderId: '1092944111670',
    projectId: 'myread-b724e',
    authDomain: 'myread-b724e.firebaseapp.com',
    databaseURL: 'https://myread-b724e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myread-b724e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkG_jkjJjGv86qdkyMOavPMrS5iPnB_tU',
    appId: '1:1092944111670:android:52367bebb3469367015097',
    messagingSenderId: '1092944111670',
    projectId: 'myread-b724e',
    databaseURL: 'https://myread-b724e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myread-b724e.firebasestorage.app',
  );

}